# Generated by Django 4.1.13 on 2024-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_type', models.FileField(default='default_value.csv', upload_to='pulse_files/')),
                ('tongue_type', models.ImageField(upload_to='tongue_images/')),
            ],
        ),
    ]
