# Generated by Django 4.1.13 on 2024-04-19 04:17

import datacollection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='pulse_type',
            field=models.FileField(default=datacollection.models.default_pulse_file, upload_to='pulse_files/'),
        ),
    ]
