# Generated by Django 4.1.13 on 2024-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_rename_tongue_image_mymodel_tongue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='pulse_type',
            field=models.FileField(default='default_value.csv', upload_to='pulse_files/'),
        ),
    ]
