# Generated by Django 4.1.13 on 2024-04-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0002_alter_mymodel_pulse_type'),
        ('datacollection', 'custom_database_backend'),
    ]

    operations = [
    ]
