# Generated by Django 4.2.11 on 2024-04-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0004_mymodel_created_at_mymodel_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='pulse_type',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='tongue_type',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='unique_id',
        ),
    ]
