# Generated by Django 4.1.13 on 2024-04-24 06:00

import datacollection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0005_remove_mymodel_created_at_remove_mymodel_pulse_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatacollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_type', models.FileField(default=datacollection.models.default_pulse_file, upload_to='pulse_type/')),
                ('tongue_type', models.ImageField(default=datacollection.models.default_pulse_file, upload_to='tongue_type/')),
                ('unique_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='models',
        ),
    ]
