# Generated by Django 4.1.13 on 2024-05-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0003_alter_mymodel_pulse_type'),
        ('datacollection', '0006_datacollectionmodel_delete_mymodel'),
    ]

    operations = [
    ]
